// Tables

Table subject {
  subject_id varchar [pk,
    note: 'Subject/Participant Identifier within project'
  ]
  dbgap_subject_id varchar [
    note: 'Subject id used by dbGaP, if available'
  ]
  consent_code varchar [ref: > consent.consent_code]
  study_nickname varchar [ref: > consent.study_nickname]
  dbgap_submission bool [
    note: 'Flag if sample has been submitted to dbGaP'
  ]
  dbgap_study_id varchar [
    note: 'PHS ID for study'
  ]
  reported_sex enum [
    note: 'reported sex'
  ]
}

Table consent {
  consent_code varchar [
    note: 'consent abbreviation (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4721915/table/pgen.1005772.t001/?report=objectonly)'
  ]
  consent_description varchar [
    note: 'longer consent description'
  ]
  DUL varchar [
    note: 'Data use limitations'
  ]
  study_nickname varchar [
    note: 'short name for study as defined by CC'
  ]
}

Table ancestry {
  subject_id varchar [ref: - subject.subject_id]
  ancestry varchar [
    note: 'ancestry category from the Human Ancestry Ontology: https://www.ebi.ac.uk/ols/ontologies/hancestro'
  ]
  ancestry_detail varchar [
    note: 'additional detail on ancestry'
  ]
  country varchar [
    note: 'country where participant data was collected'
  ]
  race varchar [
    note: 'reported race of participant defined by NIH Racial and Ethnic Categories and Definitions (NOT-OD-15-089)'
  ]
  ethnicity varchar [
    note: 'reported ethnicity of participant defined by NIH Racial and Ethnic Categories and Definitions (NOT-OD-15-089)'
  ]
}

// there will be multiple phenotype tables for different domains
// this is just an exammple
Table phenotype {
  subject_id varchar [ref: < subject.subject_id]
  age_baseline int
}

Table sample {
  sample_id varchar [pk,
    note: 'sample identifier'
  ]
  subject_id varchar [ref: < subject.subject_id]
  dbgap_sample_id varchar [
    note: 'Sample id used by dbGaP, if available'
  ]
  tissue_source varchar [
    note: 'tissue type of sample (UBERON concepts)'
  ]
  age_at_sample_collection int [
    note: 'age [] of subject when sample was collected'
  ]
  dataset_type dataset_type [
    note: 'type of dataset this sample belongs to'
  ]
}

Table sample_set {
  sample_set_id varchar [pk]
  sample_id varchar [ref: < sample.sample_id]
}

Table array_dataset {
  dataset_id [pk]
  sample_set_id varchar [ref: < sample_set.sample_set_id]
  genotyping_center varchar
  array_filename varchar
  array_manufacturer varchar
  array_name varchar
  genotype_caling_software varchar
}

Table imputation_dataset {
  dataset_id [pk]
  sample_set_id varchar [ref: < sample_set.sample_set_id]
  source_genotypes varchar
  reference_panel varchar
  imputation_pipeline varchar
  quality_filter varchar
  imputed_filename varchar
}

Table sequencing_dataset {
  dataset_id [pk]
  sample_set_id varchar [ref: < sample_set.sample_set_id]
  seq_center varchar
  reference_genome_build varchar
  alignment_method varchar
  functional_equivalence_standard varchar
  analyte_type analyte_type
  analyte_isolation_method varchar
  analyte_isolation_batch varchar
  analyte_quality_metrics varchar
  sequencing_assay varchar
  library_prep_kit_method varchar
  exome_capture_platform varchar
  capture_region_bed_filename varchar
  date_data_generation date
  sequencer_id varchar
  seq_platform varchar
  target_insert_size int
  target_depth int
  seq_strategy varchar
  read_length int
  number_of_independent_libraries int
}

Table array_file {
  md5 varchar [pk]
  dataset_id varchar [ref: < array_dataset.dataset_id]
  filename varchar
}

Table imputation_file {
  md5 varchar [pk]
  dataset_id varchar [ref: < imputation_dataset.dataset_id]
  filename varchar
}

Table sequencing_file {
  md5 varchar [pk]
  dataset_id varchar [ref: < sequencing_dataset.dataset_id]
  filename varchar
}


// Enumerated values

enum sex {
  F
  M
  X
}

enum analyte_type {
  DNA
  RNA
}

enum dataset_type {
  sequencing
  array
  imputation
}
